import type { FC, ReactNode } from "react"
import type { Metadata } from "next";
import "./globals.css";

interface RootLayoutProps {
  children: Readonly<ReactNode>
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}

export default RootLayout
